//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeSystemManagement.Web.Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_de_DE {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_de_DE() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ResumeSystemManagement.Web.Resources.Views.Home.Index_de_DE", typeof(Index_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Candidates {
            get {
                return ResourceManager.GetString("Candidates", resourceCulture);
            }
        }
        
        internal static string ColumnCreated {
            get {
                return ResourceManager.GetString("ColumnCreated", resourceCulture);
            }
        }
        
        internal static string ColumnCv {
            get {
                return ResourceManager.GetString("ColumnCv", resourceCulture);
            }
        }
        
        internal static string ColumnLevel {
            get {
                return ResourceManager.GetString("ColumnLevel", resourceCulture);
            }
        }
        
        internal static string ColumnPosition {
            get {
                return ResourceManager.GetString("ColumnPosition", resourceCulture);
            }
        }
        
        internal static string DescriptionLatePosition {
            get {
                return ResourceManager.GetString("DescriptionLatePosition", resourceCulture);
            }
        }
        
        internal static string DescriptionPopularPosition {
            get {
                return ResourceManager.GetString("DescriptionPopularPosition", resourceCulture);
            }
        }
        
        internal static string LatestPositions {
            get {
                return ResourceManager.GetString("LatestPositions", resourceCulture);
            }
        }
        
        internal static string NotLatestPosition {
            get {
                return ResourceManager.GetString("NotLatestPosition", resourceCulture);
            }
        }
        
        internal static string NotPopularPosition {
            get {
                return ResourceManager.GetString("NotPopularPosition", resourceCulture);
            }
        }
        
        internal static string TitlePopularPosition {
            get {
                return ResourceManager.GetString("TitlePopularPosition", resourceCulture);
            }
        }
        
        internal static string TotalPositions {
            get {
                return ResourceManager.GetString("TotalPositions", resourceCulture);
            }
        }
        
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
